version: '2'

services:
  server:
    build: ./docker/server
    image: afnphpframework_web
    ports:
      - "6014:80"
      - "4412:443"
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./library:/var/www/library
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./scripts:/var/www/scripts
      - ./storage:/var/www/storage
      - ./temp:/var/www/temp
      - ./www:/var/www/html
      - ./mail/msmtprc:/etc/msmtprc
    links:
      - db
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=172.22.0.2
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=test
    restart: always
    ports:
      - 6016:80
    links:
      - "db:mysql"
    tty: true

  db:
    image: mysql:5.6
    ports:
      - "3408:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=db_afntest
    tty: true
